// reviewSandbox.js — the storage side of the sandbox: writing the declared
// layout into the project's file store, linking documents to records, and the
// umbrella review's children. The shape lives in reviewSandboxModel.js so it
// can be tested without a browser.

import { putFile, getFile, listFiles, getProject, createProject } from "./projectstore.js";
import { loadReview, saveReview } from "./reviewengine.js";
import { PATHS, slug, toYaml, buildManifest, parseYaml, reviewFromManifest } from "./reviewSandboxModel.js";

export * from "./reviewSandboxModel.js";

// --- writing the sandbox ---------------------------------------------------

/** Writes the declared layout into the project's file store. Idempotent. */
export function materializeSandbox(projectId, { children = [] } = {}) {
  const review = loadReview(projectId);
  if (!review) return { ok: false, reason: "no review in this project" };
  const project = getProject(projectId);
  const manifest = buildManifest(review, { project, children });
  const written = [];

  const write = (path, content, type = "text") => {
    putFile(projectId, { path, name: path.split("/").pop(), type, content });
    written.push(path);
  };

  write(PATHS.manifest, `# Generated by Medantir. The layout is the contract.\n${toYaml(manifest)}\n`, "yaml");
  write(PATHS.question, toYaml({
    question: review.question || null,
    prism: review.protocol?.prism?.facets || null,
    pico: review.protocol?.pico || null,
    design: review.protocol?.pico?.studyDesign || null,
  }), "yaml");
  if (review.objects?.eligibility) write(PATHS.eligibility, review.objects.eligibility, "markdown");
  write(PATHS.records, JSON.stringify(review.objects?.records || [], null, 2), "json");

  for (const search of review.objects?.searches || []) {
    const name = search.name || search.db;
    if (search.query) write(PATHS.strategy(name), `${search.query}\n`, "text");
  }

  for (const record of review.objects?.records || []) {
    if (record.fullText) write(PATHS.fulltextText(record.id), record.fullText, "text");
    if (record.files?.pdf) {
      write(PATHS.fulltextLink(record.id), toYaml({
        record: record.id,
        title: record.title || null,
        path: record.files.pdf,
        bytes: record.files.pdfBytes ?? null,
        sha256: record.files.pdfHash || null,
        linked: record.files.linkedAt ? new Date(record.files.linkedAt).toISOString() : null,
        note: "The PDF itself stays where it is; this file records where that is.",
      }), "yaml");
    }
  }

  for (const study of review.objects?.studies || []) {
    const folder = PATHS.study(study.id);
    if (study.extraction) write(`${folder}/extraction.yaml`, toYaml(study.extraction), "yaml");
    if (study.rob) write(`${folder}/rob.yaml`, toYaml(study.rob), "yaml");
  }

  return { ok: true, manifest, written };
}

// --- importing a sandbox ---------------------------------------------------

/**
 * Rebuilds a review in this workspace from a review.yaml a sandbox produced.
 * The manifest is the contract, so importing it is the inverse of writing it:
 * the same layout is materialized again on the way in, which is also the check
 * that what was read can be written back.
 *
 * `records` and `eligibility` are the two things the manifest points at rather
 * than contains. Supply them (records/records.json, protocol/eligibility.md)
 * and the review arrives whole; omit them and it arrives without them.
 */
export function importSandbox(yamlText, { name = "", records = [], eligibility = "" } = {}) {
  let manifest;
  try {
    manifest = parseYaml(yamlText);
  } catch (cause) {
    return { ok: false, reason: `could not read the manifest: ${cause?.message || cause}` };
  }
  if (!manifest || typeof manifest !== "object" || !manifest.review) {
    return { ok: false, reason: "this file has no review: block — it is not a Medantir review.yaml" };
  }
  const { review, children, title } = reviewFromManifest(manifest, { records, eligibility });
  const project = createProject(String(name || "").trim() || title || "Imported review", {
    projectType: "systematic-review",
    mode: "academic",
  });
  saveReview(project.id, review);
  if (children.length) {
    putFile(project.id, { path: CHILDREN_KEY, name: CHILDREN_KEY, type: "json", content: JSON.stringify(children, null, 2) });
  }
  const written = materializeSandbox(project.id, { children });
  return { ok: true, projectId: project.id, project, review, children, manifest, written: written.written || [] };
}

/**
 * Link a document to a record. The bytes are not copied: what is recorded is
 * where the file is, how big it is, its hash, and the text the pipeline reads.
 */
export async function linkDocument(projectId, recordId, { path, bytes, hash, text, pages }) {
  const review = loadReview(projectId);
  if (!review) return { ok: false, reason: "no review in this project" };
  const records = (review.objects?.records || []).map((r) => (
    r.id === recordId
      ? {
        ...r,
        files: { ...(r.files || {}), pdf: path || r.files?.pdf || null, pdfBytes: bytes ?? r.files?.pdfBytes ?? null, pdfHash: hash || r.files?.pdfHash || null, text: PATHS.fulltextText(recordId), linkedAt: Date.now() },
        ...(text ? { fullText: text, fullTextPages: pages ?? r.fullTextPages ?? null, retrieval: "retrieved" } : {}),
      }
      : r
  ));
  const next = { ...review, objects: { ...review.objects, records } };
  saveReview(projectId, next);
  if (text) putFile(projectId, { path: PATHS.fulltextText(recordId), name: `${slug(recordId)}.txt`, type: "text", content: text });
  return { ok: true, review: next };
}

export async function sha256Hex(buffer) {
  try {
    const digest = await crypto.subtle.digest("SHA-256", buffer);
    return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
  } catch {
    return null;
  }
}

// --- umbrella children -----------------------------------------------------

const CHILDREN_KEY = "children.json";

export function listChildReviews(projectId) {
  const file = getFile(projectId, CHILDREN_KEY);
  if (!file) return [];
  try { return JSON.parse(file.content); } catch { return []; }
}

/**
 * An umbrella review's unit of analysis is a review, and each included review
 * brings its own primaries. Recording them separately is what makes an overlap
 * check (CCA) possible later — pooling them into one flat record list destroys
 * exactly the structure that matters.
 */
export function addChildReview(projectId, { title, doi, primaries = [], year, overlapChecked = false }) {
  const children = listChildReviews(projectId);
  const id = slug(`${title}-${year || ""}`);
  if (children.some((c) => c.id === id)) return { ok: false, reason: "a review with that title and year is already included", children };
  const child = { id, title, doi: doi || null, year: year || null, primaries: primaries.length, primaryIds: primaries, overlapChecked, addedAt: Date.now() };
  const next = [...children, child];
  putFile(projectId, { path: CHILDREN_KEY, name: CHILDREN_KEY, type: "json", content: JSON.stringify(next, null, 2) });
  putFile(projectId, {
    path: `${PATHS.child(id)}/review.yaml`,
    name: "review.yaml",
    type: "yaml",
    content: toYaml({ review: { title, doi: doi || null, year: year || null, unit: "included review" }, primaries }),
  });
  return { ok: true, child, children: next };
}

export function removeChildReview(projectId, id) {
  const next = listChildReviews(projectId).filter((c) => c.id !== id);
  putFile(projectId, { path: CHILDREN_KEY, name: CHILDREN_KEY, type: "json", content: JSON.stringify(next, null, 2) });
  return next;
}

// --- reading the sandbox back ---------------------------------------------

export function sandboxTree(projectId) {
  const files = listFiles(projectId) || [];
  const tree = {};
  for (const file of files) {
    const parts = String(file.path || file.name).split("/");
    let node = tree;
    for (let i = 0; i < parts.length - 1; i++) {
      node[parts[i]] = node[parts[i]] || { __dir: true };
      node = node[parts[i]];
    }
    node[parts[parts.length - 1]] = { __file: true, path: file.path, size: (file.content || "").length, type: file.type };
  }
  return tree;
}
