apiVersion: v1
kind: Namespace
metadata:
  name: medantir-evidence
  labels:
    app.kubernetes.io/name: medantir-evidence
    app.kubernetes.io/part-of: medantir-evidence-os
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
