apiVersion: v1
kind: ServiceAccount
metadata:
  name: medantir-evidence
  namespace: medantir-evidence
  labels:
    app.kubernetes.io/name: medantir-evidence
    app.kubernetes.io/part-of: medantir-evidence-os
automountServiceAccountToken: false
